### ISSUE TITLE
Make a registration page 

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#1]
Find the old registration form for season 4, and make a form that duplicates that information for a given league and make a version of this that works.

**Comment by cyanfish** [comment]
I'll grab this one since I've been thinking about it already.

**Comment by cyanfish** [comment]
Something we may want to do when mods approve a registration is automatically invite the user to Slack using the undocumented [users.admin.invite](https://github.com/ErikKalkoken/slackApiDoc/blob/master/users.admin.invite.md) API method.

**Comment by lakinwecker** [comment]
Sure. That's a good idea.

**Comment by cyanfish** [comment]
Closing since this is functional.
