### ISSUE TITLE
Interview lonewolf and 45+45 mods

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#10]
We should go through the weekly activities that these mods do, and make a list of "use cases" that we need to support for them and ensure the django admin supports them.

**Comment by cyanfish** [comment]
One thing in particular to talk about: Alternate management.

**Comment by cyanfish** [comment]
We've scheduled a meeting for Saturday 07/30 at 20:00 GMT.

**Comment by cyanfish** [comment]
The transcript from this meeting is pinned in our Slack channel.
