### ISSUE TITLE
Define what the home page should show

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#2]
What should the home page show?  Probably any active season standings (or links to them), plus a link to any "registration" if any are open, + link to rules / info about the league.

**Comment by endrawes0** [comment]
Link to tv if we ever get it done.
Link to slack.
Contact for moderators/admins - maybe registration is good enough...

**Comment by cyanfish** [comment]
We have a dynamic home page mostly implemented. Any additional changes can have a new issue created.
