### ISSUE TITLE
Add Notes fields to more models

### ISSUE THREAD

**Issue by cyanfish** [krystjan/heltour#22]
Mods should be able to leave unstructured comments for future reference. On anything that makes sense - players, teams, pairings, etc.

**Comment by cyanfish** [comment]
We could also consider using something like [django-notes](https://github.com/powellc/django-notes) to separate out multiple notes for a model. That way concurrently adding a note would just result in two new notes.

**Comment by lakinwecker** [comment]
Yeah, I think we should consider something like that, but in this case, it says that django-notes is unmaintained.   I haven't been able to find a better version of an app like this at all.

What about a disqus type forum that's only enabled for admins, but is on each page?

**Comment by cyanfish** [comment]
I looked at the source for that app and it's pretty basic. It has a note model that ties into other models using a generic relation and integrates into the admin pages by using the inlines feature. We could probably implement something like that ourselves.

A more proper forum would be better, but I'm not sure how easy it would be to integrate.

**Comment by lakinwecker** [comment]
I understand your points.  Implementing something that simple should likely work.  Another option is using this: http://django-disqus.readthedocs.io/en/latest/templatetags.html

And then overriding the admin template tags and dropping a disqus forum on the various change-object pages.

I'm not sure which I think is a better approach. I like the simplicity of rolling our own simple version, but everytime I've done that in the past I've ended up eventually replacing it with a pre-built forum eventually.

**Comment by cyanfish** [comment]
I'm open to using some kind of prebuilt solution, but I'm not sure about Disqus specifically. It doesn't seem to have a great track record for privacy, and I'd rather have something we can host on our own server.

**Comment by cyanfish** [comment]
I've implemented this using the django_comments app. It required a bit of customization but I think it's pretty much what we were looking for.
