### ISSUE TITLE
API for welcome message

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#32]
Chesster currently sends a welcome message to everyone that joins slack. Right now we have to redeploy chesster each time we want to change that message. 

I am thinking that the current seasons can have a "Welcome" message on them, and chesster can ask the API for the current "welcome messages" and pass that along to the new signups.  this way the mods can control that message from the heltour admin. Thoughts?

**Comment by cyanfish** [comment]
That should be easy enough to implement. We already have a LeagueDocument model we can leverage, we would just need to create a new document type. We could also create a SeasonDocument model if it's needed.

The only downside is that the document editor is designed for HTML, so either the tags would have to be stripped or the document would need to be edited in source mode.

**Comment by cyanfish** [comment]
I've implemented a "league_document" endpoint, documented on the [wiki](https://github.com/krystjan/heltour/wiki/API-Endpoints).

You can use "type=slack-welcome", and create/edit a LeagueDocument with that type in the django admin.
