### ISSUE TITLE
Prioritize lichess API requests

### ISSUE THREAD

**Issue by cyanfish** [krystjan/heltour#39]
Requests coming from chesster (e.g. to validate game links) need a higher priority over background rating updates.

**Comment by cyanfish** [comment]
I'm thinking that a true cross-process priority queue or independent lichess API worker would be fairly difficult to implement.

A simpler solution might be to use a cross-process lock on the lichess API layer, and then for low-priority requests, wait a brief period (e.g. 0.5 seconds) between calls to the API layer. That way any higher-priority requests waiting for the lock shouldn't have to worry about contention from the low-priority requests.

This assumes that there's only one thread running low-priority requests at a time, which is probably reasonable.

**Comment by lakinwecker** [comment]
Hrmm. a single-thread worker versus a single-process worker seems to be the same level of complexity.  At least I don't see the savings on complexity.  Also, by making it a separate process we ease some amount of deployment concerns.

Cross-process coordination is the issue, but unless we guarantee that the deployment will always be a single django process/thread (it's not currently) then we have similar issues that we have to solve anyways.

I'd be happy to discuss some thoughts on how to implement this.

**Comment by cyanfish** [comment]
I think the worker still needs to be set up on the live server, but otherwise it's implemented.
