### ISSUE TITLE
API: Get roster for a league

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#4]
There should be an API method to allow chesster to refresh the current roster for a given league.

This should include information about all players that are registered all teams that are formed and their members/captains. 

It should also include information about alternates.

**Comment by lakinwecker** [comment]
I'm ok if this is a series of API calls so that the the initial one simply returns the basic information for a league and you can get subsequent information from a series of other calls, but I think I'm leaning towards a single shot get all information call. Makes programming chesster easier.

**Comment by cyanfish** [comment]
I've pushed an initial implementation of the get_roster method (documented on the [wiki](https://github.com/krystjan/heltour/wiki/API-Endpoints)). It currently provides information about players and teams but no explicit information about alternates.

**Comment by cyanfish** [comment]
https://github.com/krystjan/heltour/issues/17
