### ISSUE TITLE
Make a season landing page

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#5]
There should be a landing page for each season in the league. The season page should show or link to the standings, the results and the current pairings (if they exist).  

We can probably design it after the lichess tournament pages in that after a season is done, first second and third place get a "trophy" at the top.

**Comment by cyanfish** [comment]
I have a season landing page implemented, but it's designed around an active season. We should have an alternative view for completed seasons.

**Comment by cyanfish** [comment]
https://github.com/krystjan/heltour/issues/19
