### ISSUE TITLE
League switcher

### ISSUE THREAD

**Issue by cyanfish** [krystjan/heltour#56]
There should be some kind of way to navigate between leagues. We should also consider whether we want there to be a "default" league and if we should require the "/team4545/" and "/lonewolf/" url prefixes (with "/" being either a neutral home page or a redirect to the default league).

**Comment by lakinwecker** [comment]
I am favour of the index page showing you all active seasons for leagues with an icon/name, and allowing to click which you want to go to and having all urls from there on out specific the league tag.

**Comment by cyanfish** [comment]
I've made the change to URLs and added a home page. All it has right now is links to each league. At some point we could add a TV widget as well.

You can switch leagues by clicking on the new links on each league home page, or by clicking twice on the top left title.
