### ISSUE TITLE
Design / look of the site

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#7]
I don't know if we have any designers amongst our midst. I should not be let anywhere near design, but we should come up with basic look and feel for the site. 

I am leaning towards making it mobile optimized first with the full desktop view coming second.  With that in mind, unless someone is willing to take on the job of doing all of the design, we should probably use something pre-built. 

If it was up to me, I would pick some colours from Adobe Kuler, jam them into a custom Foundation CSS build and then build the site on the foundation grid with an eye towards making it super mobile friendly first.  Using foundation means using jquery to get access to their plugins, but I'm fine with that.

**Comment by lakinwecker** [comment]
Also, using foundation might also be easier to do using django-templates for HTML production rather than something like mithril - but I'm not certain. I'm happy to go either way

**Comment by cyanfish** [comment]
I already added Bootstrap to the project instead of Foundation since that's what I'm familiar with. If we get someone that wants to own the design they can use whichever they prefer, but if not, I can find and modify some Bootstrap template to suit us.

**Comment by lakinwecker** [comment]
:+1: to bootstrap. Especially if you're familiar with it.

**Comment by cyanfish** [comment]
I've created an updated design. I'm happy enough with it, so I'm going to close this issue, but we can reopen it if someone else comes on board and wants to improve the design further.
