### ISSUE TITLE
Make a python script to populate our db from the current spreadsheet

### ISSUE THREAD

**Issue by lakinwecker** [krystjan/heltour#9]
It would be super beneficial for testing to have a script we can run on that populates the database from the current spreadsheet.

Also, unless we manage to time this perfectly, it's likely we'll launch in the middle of a season and will have to do this migration anyways.

**Comment by cyanfish** [comment]
I've committed a working prototype of the spreadsheet import. Instructions:

Setup
1. Create a [google service account key](http://gspread.readthedocs.io/en/latest/oauth2.html)
2. Set GOOGLE_SERVICE_ACCOUNT_KEYFILE_PATH in your settings.py to point to your private key file
3. Create a copy of the Lichess Season 4 spreadsheet and share it (with edit access) to the client_email specified in your key file

Import
1. Create a league (if you don't have one already)
2. In the league list, perform the "Import season" action on your league
3. Enter the URL to the spreadsheet you created in the setup
4. Fill in the other fields as you like and click Import

**Comment by lakinwecker** [comment]
Works great!

**Comment by lakinwecker** [comment]
Calling this done.
